In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
%matplotlib inline
import io

In [0]:
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble
from sklearn.externals import joblib

import xgboost, textblob, string
from keras.preprocessing import text, sequence
from keras import layers, models, optimizers

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
Using TensorFlow backend.

In [0]:
import gensim 
from gensim.models import Word2Vec
import nltk

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
# read file into pandas
df = pd.read_csv('/content/drive/My Drive/brazilian-malware.csv')

In [0]:
# examine the shape
df.shape

(50181, 28)

In [0]:
# examine the first 10 rows
df.head()

   BaseOfCode  BaseOfData  ...  SizeOfUninitializedData  TimeDateStamp
0        4096       69632  ...                     1500          12345
1        4096     1851392  ...                    21476              0
2        4096       40960  ...                 33557504              0
3     1359872     2138112  ...                  1355776              0
4        4096       40960  ...                   110080              0

[5 rows x 28 columns]

In [0]:
df = df.drop('SHA1', 1)

In [0]:
df = df.drop('FirstSeenDate', 1)

In [0]:
df = df.drop('PE_TYPE', 1)

In [0]:
df = df.drop('Identify', 1)

In [0]:
df = df.drop('Magic', 1)

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
v = TfidfVectorizer()
x = v.fit_transform(df['ImportedDlls'])
df['ImportedDlls'] = list(x.toarray())

In [0]:
#this gives memory error and hence skiping this and using word2vec instead 
u = TfidfVectorizer()
y = u.fit_transform(df['ImportedSymbols'])
df['ImportedSymbols'] = list(y.toarray())

In [0]:
df.head()

   BaseOfCode  BaseOfData  ...  SizeOfUninitializedData  TimeDateStamp
0        4096       69632  ...                     1500          12345
1        4096     1851392  ...                    21476              0
2        4096       40960  ...                 33557504              0
3     1359872     2138112  ...                  1355776              0
4        4096       40960  ...                   110080              0

[5 rows x 23 columns]

In [0]:
df = df.drop('ImportedDlls', 1)
df = df.drop('ImportedSymbols', 1)

In [0]:
df.head()

   BaseOfCode  BaseOfData  ...  SizeOfUninitializedData  TimeDateStamp
0        4096       69632  ...                     1500          12345
1        4096     1851392  ...                    21476              0
2        4096       40960  ...                 33557504              0
3     1359872     2138112  ...                  1355776              0
4        4096       40960  ...                   110080              0

[5 rows x 21 columns]

In [0]:
# examine the class distribution
df.Label.value_counts()

1    29065
0    21116
Name: Label, dtype: int64

In [0]:
# how to define X and y for use with COUNTVECTORIZER
X = df.drop('Label', 1)
y = df.Label
print(X.shape)
print(y.shape)
print(df.shape)

(50181, 20)
(50181,)
(50181, 21)

In [0]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(37635, 20)
(12546, 20)
(37635,)
(12546,)

In [0]:
from sklearn.ensemble import RandomForestRegressor

In [0]:
regressor = RandomForestRegressor(n_estimators = 100, random_state = 10)

In [0]:
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=10, verbose=0, warm_start=False)

In [0]:
regressor.score(X_test, y_test)

0.9566788369299084

In [0]:
def Recommendation(testdata):
  pred = regressor.predict(testdata)
  print(pred)
  for i in pred:
    if i < 0.3:
      print("Low")
    elif i < 0.6:
      print("Medium")
    else:
      print("High")

In [0]:
X_test = pd.read_csv('/content/drive/My Drive/test1.csv')
X_test.drop(columns=['ImportedDlls','ImportedSymbols','Magic'],inplace=True)

In [0]:
Y_test = np.zeros(15)

In [0]:
pred = regressor.predict(X_test)
pred

array([0.        , 0.08666667, 0.04      , 0.89      , 0.6       ,
       0.04      , 0.        , 0.19933333, 0.05      , 0.06      ,
       0.03      , 0.1       , 0.07      , 0.01      , 0.17      ])

In [0]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(Y_test, pred.round())
print(conf_mat)

[[13  2]
 [ 0  0]]

In [0]:
#Recommendation for Test1.csv
Recommendation(X_test)

[0.         0.08666667 0.04       0.89       0.6        0.04
 0.         0.19933333 0.05       0.06       0.03       0.1
 0.07       0.01       0.17      ]
Low
Low
Low
High
High
Low
Low
Low
Low
Low
Low
Low
Low
Low
Low

In [0]:
X_test = pd.read_csv('/content/drive/My Drive/test2.csv')
X_test.drop(columns=['ImportedDlls','ImportedSymbols','Magic'],inplace=True)

In [0]:
Y_test = np.ones(15)

In [0]:
pred = regressor.predict(X_test)
pred

array([0.02, 0.84, 1.  , 1.  , 0.93, 0.5 , 0.88, 0.9 , 0.78, 0.57, 0.99,
       0.99, 0.92, 0.86, 0.45])

In [0]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(Y_test, pred.round())
print(conf_mat)

[[ 0  0]
 [ 3 12]]

In [0]:
#Recommendation for Test1.csv
Recommendation(X_test)

[0.02 0.84 1.   1.   0.93 0.5  0.88 0.9  0.78 0.57 0.99 0.99 0.92 0.86
 0.45]
Low
High
High
High
High
Medium
High
High
High
Medium
High
High
High
High
Medium